name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test
  
  version:
    name: Version Bump
    needs: test
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        id: import_gpg
        with:
          gpg_private_key: ${{secrets.GPG_KEY}}
          passphrase: ${{secrets.GPG_PASS}}
          git_committer_name: ${{secrets.GIT_NAME}}
          git_committer_email: ${{secrets.GIT_EMAIL}}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Push new version
        run: |
          git config --local gpg.program $(which gpg)
          git remote set-url origin "https://${{secrets.GIT_NAME}}:${{secrets.GIT_TOKEN}}@github.com/$GITHUB_REPOSITORY"
          yarn release
          git push --follow-tags origin main
  
  publish-gpr:
    name: Publish to Github Packages
    needs: test
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: borales/actions-yarn@v2.3.0
        name: Build library
        with:
          cmd: build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
