name: test

on: [workflow_call]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test