name: test

on: [workflow_call]

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test